// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChildGTS_Group02.DAL.Entities;

public partial class Blog
{
    public int BlogId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int? AuthorId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string Status { get; set; }

    public string Category { get; set; }

    public int? Views { get; set; }

    public int? Likes { get; set; }

    public string FeaturedImage { get; set; }

    public virtual User Author { get; set; }
}