// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChildGTS_Group02.DAL.Entities;

public partial class Child
{
    public int ChildId { get; set; }

    public int ParentId { get; set; }

    public string FullName { get; set; }

    public DateOnly DateOfBirth { get; set; }

    public string Gender { get; set; }

    public decimal? BirthWeight { get; set; }

    public decimal? BirthHeight { get; set; }

    public string ProfileImage { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastCheckupDate { get; set; }

    public string MedicalNotes { get; set; }

    public virtual ICollection<DataShare> DataShares { get; set; } = new List<DataShare>();

    public virtual ICollection<GrowthRecord> GrowthRecords { get; set; } = new List<GrowthRecord>();

    public virtual ICollection<HealthAlert> HealthAlerts { get; set; } = new List<HealthAlert>();

    public virtual User Parent { get; set; }
}