// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChildGTS_Group02.DAL.Entities;

public partial class DataShare
{
    public int ShareId { get; set; }

    public int ChildId { get; set; }

    public int DoctorId { get; set; }

    public DateTime? ShareDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string AccessLevel { get; set; }

    public DateTime? LastAccessed { get; set; }

    public string ShareStatus { get; set; }

    public virtual Child Child { get; set; }

    public virtual User Doctor { get; set; }

    public virtual ICollection<DoctorFeedback> DoctorFeedbacks { get; set; } = new List<DoctorFeedback>();
}