// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChildGTS_Group02.DAL.Entities;

public partial class DoctorFeedback
{
    public int FeedbackId { get; set; }

    public int GrowthRecordId { get; set; }

    public DateTime? FeedbackDate { get; set; }

    public string Comments { get; set; }

    public string Recommendations { get; set; }

    public int? Rating { get; set; }

    public DateTime? FollowUpDate { get; set; }

    public string Status { get; set; }

    public string Attachments { get; set; }

    public string Priority { get; set; }

    public bool? ParentAcknowledged { get; set; }

    public virtual ICollection<FeedbackRating> FeedbackRatings { get; set; } = new List<FeedbackRating>();

    public virtual GrowthRecord GrowthRecord { get; set; }
}