// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChildGTS_Group02.DAL.Entities;

public partial class FeedbackRating
{
    public int RatingId { get; set; }

    public int FeedbackId { get; set; }

    public int UserId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? RatingDate { get; set; }

    public int? HelpfulCount { get; set; }

    public int? ReportCount { get; set; }

    public string Status { get; set; }

    public virtual DoctorFeedback Feedback { get; set; }

    public virtual User User { get; set; }
}