// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChildGTS_Group02.DAL.Entities;

public partial class HealthAlert
{
    public int AlertId { get; set; }

    public int ChildId { get; set; }

    public string AlertType { get; set; }

    public string AlertMessage { get; set; }

    public string Severity { get; set; }

    public DateTime? GeneratedDate { get; set; }

    public bool? Acknowledged { get; set; }

    public int? AcknowledgedBy { get; set; }

    public string ResolutionStatus { get; set; }

    public int? RelatedRecordId { get; set; }

    public string FollowUpActions { get; set; }

    public virtual User AcknowledgedByNavigation { get; set; }

    public virtual Child Child { get; set; }
}