// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChildGTS_Group02.DAL.Entities;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int UserId { get; set; }

    public int PackageId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string Status { get; set; }

    public DateTime? TransactionDate { get; set; }

    public string TransactionId { get; set; }

    public string Notes { get; set; }

    public string InvoiceNumber { get; set; }

    public string PaymentDetails { get; set; }

    public virtual MembershipPackage Package { get; set; }

    public virtual User User { get; set; }
}