// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ChildGTS_Group02.DAL.Entities;

public partial class User
{
    public int UserId { get; set; }

    public int RoleId { get; set; }

    [Required(ErrorMessage = "Email is required.")]
    [EmailAddress(ErrorMessage = "Invalid email format.")]
    public string Email { get; set; }

    [Required(ErrorMessage = "Password is required.")]
    [MinLength(6, ErrorMessage = "Password must be at least 6 characters long.")]
    public string Password { get; set; }

    [Required(ErrorMessage = "Full Name is required.")]
    public string FullName { get; set; }

    [Required(ErrorMessage = "Phone is required.")]
    [RegularExpression(@"^\d+$", ErrorMessage = "Phone number must contain only digits.")]
    [MinLength(10, ErrorMessage = "Phone number must be at least 10 digits.")]
    [MaxLength(10, ErrorMessage = "Phone number cannot exceed 10 digits.")]
    public string Phone { get; set; }

    public string DoctorCode { get; set; }

    public string DoctorPosition { get; set; }

    [Required(ErrorMessage = "Address is required.")]
    public string Address { get; set; }

    public DateTime? RegistrationDate { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsTrial { get; set; }

    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();

    public virtual ICollection<Child> Children { get; set; } = new List<Child>();

    public virtual ICollection<DataShare> DataShares { get; set; } = new List<DataShare>();

    public virtual ICollection<FeedbackRating> FeedbackRatings { get; set; } = new List<FeedbackRating>();

    public virtual ICollection<HealthAlert> HealthAlerts { get; set; } = new List<HealthAlert>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Role Role { get; set; }
}