// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChildGTS_Group02.DAL.Entities;

public partial class User
{
    public int UserId { get; set; }

    public int RoleId { get; set; }

    public int? PositionId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public string DoctorCode { get; set; }

    public string Address { get; set; }

    public DateTime? RegistrationDate { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsTrial { get; set; }

    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();

    public virtual ICollection<Child> Children { get; set; } = new List<Child>();

    public virtual ICollection<DataShare> DataShares { get; set; } = new List<DataShare>();

    public virtual ICollection<FeedbackRating> FeedbackRatings { get; set; } = new List<FeedbackRating>();

    public virtual ICollection<HealthAlert> HealthAlerts { get; set; } = new List<HealthAlert>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual DoctorPosition Position { get; set; }

    public virtual Role Role { get; set; }
}