// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace ChildGTS_Group02.DAL.Entities;

public partial class ChildGrowthTrackingSystemDBContext : DbContext
{
    public ChildGrowthTrackingSystemDBContext(DbContextOptions<ChildGrowthTrackingSystemDBContext> options)
        : base(options)
    {
    }

    public ChildGrowthTrackingSystemDBContext()
    {
    }

    public virtual DbSet<Blog> Blogs { get; set; }

    public virtual DbSet<Child> Children { get; set; }

    public virtual DbSet<DataShare> DataShares { get; set; }

    public virtual DbSet<DoctorFeedback> DoctorFeedbacks { get; set; }

    public virtual DbSet<DoctorPosition> DoctorPositions { get; set; }

    public virtual DbSet<FeedbackRating> FeedbackRatings { get; set; }

    public virtual DbSet<GrowthRecord> GrowthRecords { get; set; }

    public virtual DbSet<HealthAlert> HealthAlerts { get; set; }

    public virtual DbSet<MembershipPackage> MembershipPackages { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    private string GetConnectionString()
    {
        IConfiguration config = new ConfigurationBuilder()
             .SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile("appsettings.json", true, true)
                    .Build();
        var strConn = config["ConnectionStrings:DefaultConnection"];


        return strConn;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(GetConnectionString());
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>(entity =>
        {
            entity.HasKey(e => e.BlogId).HasName("PK__Blog__54379E50DA344FDE");

            entity.ToTable("Blog");

            entity.Property(e => e.BlogId).HasColumnName("BlogID");
            entity.Property(e => e.AuthorId).HasColumnName("AuthorID");
            entity.Property(e => e.Category).HasMaxLength(50);
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FeaturedImage).HasMaxLength(255);
            entity.Property(e => e.Likes).HasDefaultValue(0);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("Draft");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.Views).HasDefaultValue(0);

            entity.HasOne(d => d.Author).WithMany(p => p.Blogs)
                .HasForeignKey(d => d.AuthorId)
                .HasConstraintName("FK__Blog__AuthorID__70DDC3D8");
        });

        modelBuilder.Entity<Child>(entity =>
        {
            entity.HasKey(e => e.ChildId).HasName("PK__Child__BEFA07363B262668");

            entity.ToTable("Child");

            entity.Property(e => e.ChildId).HasColumnName("ChildID");
            entity.Property(e => e.BirthHeight).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.BirthWeight).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Gender).HasMaxLength(10);
            entity.Property(e => e.LastCheckupDate).HasColumnType("datetime");
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
            entity.Property(e => e.ProfileImage).HasMaxLength(255);

            entity.HasOne(d => d.Parent).WithMany(p => p.Children)
                .HasForeignKey(d => d.ParentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Child__ParentID__4D94879B");
        });

        modelBuilder.Entity<DataShare>(entity =>
        {
            entity.HasKey(e => e.ShareId).HasName("PK__DataShar__D32A3F8EFFC9F5B4");

            entity.ToTable("DataShare");

            entity.Property(e => e.ShareId).HasColumnName("ShareID");
            entity.Property(e => e.AccessLevel).HasMaxLength(20);
            entity.Property(e => e.ChildId).HasColumnName("ChildID");
            entity.Property(e => e.DoctorId).HasColumnName("DoctorID");
            entity.Property(e => e.ExpiryDate).HasColumnType("datetime");
            entity.Property(e => e.LastAccessed).HasColumnType("datetime");
            entity.Property(e => e.ShareDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ShareStatus)
                .HasMaxLength(20)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Child).WithMany(p => p.DataShares)
                .HasForeignKey(d => d.ChildId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DataShare__Child__5DCAEF64");

            entity.HasOne(d => d.Doctor).WithMany(p => p.DataShares)
                .HasForeignKey(d => d.DoctorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DataShare__Docto__5EBF139D");
        });

        modelBuilder.Entity<DoctorFeedback>(entity =>
        {
            entity.HasKey(e => e.FeedbackId).HasName("PK__DoctorFe__6A4BEDF6ABC26604");

            entity.ToTable("DoctorFeedback");

            entity.Property(e => e.FeedbackId).HasColumnName("FeedbackID");
            entity.Property(e => e.Comments).IsRequired();
            entity.Property(e => e.FeedbackDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FollowUpDate).HasColumnType("datetime");
            entity.Property(e => e.ParentAcknowledged).HasDefaultValue(false);
            entity.Property(e => e.Priority).HasMaxLength(20);
            entity.Property(e => e.ShareId).HasColumnName("ShareID");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("Pending");

            entity.HasOne(d => d.Share).WithMany(p => p.DoctorFeedbacks)
                .HasForeignKey(d => d.ShareId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DoctorFee__Share__6477ECF3");
        });

        modelBuilder.Entity<DoctorPosition>(entity =>
        {
            entity.HasKey(e => e.PositionId).HasName("PK__DoctorPo__60BB9A59CA0A5C14");

            entity.ToTable("DoctorPosition");

            entity.HasIndex(e => e.PositionName, "UQ__DoctorPo__E46AEF42E0ABBDBA").IsUnique();

            entity.Property(e => e.PositionId).HasColumnName("PositionID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PositionName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<FeedbackRating>(entity =>
        {
            entity.HasKey(e => e.RatingId).HasName("PK__Feedback__FCCDF85C169DEF3F");

            entity.ToTable("FeedbackRating");

            entity.Property(e => e.RatingId).HasColumnName("RatingID");
            entity.Property(e => e.Comment).HasMaxLength(500);
            entity.Property(e => e.FeedbackId).HasColumnName("FeedbackID");
            entity.Property(e => e.HelpfulCount).HasDefaultValue(0);
            entity.Property(e => e.RatingDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ReportCount).HasDefaultValue(0);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("Active");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Feedback).WithMany(p => p.FeedbackRatings)
                .HasForeignKey(d => d.FeedbackId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FeedbackR__Feedb__778AC167");

            entity.HasOne(d => d.User).WithMany(p => p.FeedbackRatings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FeedbackR__UserI__787EE5A0");
        });

        modelBuilder.Entity<GrowthRecord>(entity =>
        {
            entity.HasKey(e => e.RecordId).HasName("PK__GrowthRe__FBDF78C9F32F7965");

            entity.ToTable("GrowthRecord");

            entity.Property(e => e.RecordId).HasColumnName("RecordID");
            entity.Property(e => e.Bmi)
                .HasComputedColumnSql("([Weight]/(([Height]/(100))*([Height]/(100))))", false)
                .HasColumnType("decimal(37, 22)")
                .HasColumnName("BMI");
            entity.Property(e => e.ChildId).HasColumnName("ChildID");
            entity.Property(e => e.HeadCircumference).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Height).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.MeasurementType).HasMaxLength(50);
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.RecordDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.RecordedBy).HasMaxLength(20);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("Active");
            entity.Property(e => e.Weight).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Child).WithMany(p => p.GrowthRecords)
                .HasForeignKey(d => d.ChildId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GrowthRec__Child__52593CB8");
        });

        modelBuilder.Entity<HealthAlert>(entity =>
        {
            entity.HasKey(e => e.AlertId).HasName("PK__HealthAl__EBB16AED826B3EBA");

            entity.ToTable("HealthAlert");

            entity.Property(e => e.AlertId).HasColumnName("AlertID");
            entity.Property(e => e.Acknowledged).HasDefaultValue(false);
            entity.Property(e => e.AlertMessage)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.AlertType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ChildId).HasColumnName("ChildID");
            entity.Property(e => e.FollowUpActions).HasMaxLength(500);
            entity.Property(e => e.GeneratedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.RelatedRecordId).HasColumnName("RelatedRecordID");
            entity.Property(e => e.ResolutionStatus).HasMaxLength(20);
            entity.Property(e => e.Severity).HasMaxLength(20);

            entity.HasOne(d => d.AcknowledgedByNavigation).WithMany(p => p.HealthAlerts)
                .HasForeignKey(d => d.AcknowledgedBy)
                .HasConstraintName("FK__HealthAle__Ackno__5AEE82B9");

            entity.HasOne(d => d.Child).WithMany(p => p.HealthAlerts)
                .HasForeignKey(d => d.ChildId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__HealthAle__Child__571DF1D5");
        });

        modelBuilder.Entity<MembershipPackage>(entity =>
        {
            entity.HasKey(e => e.PackageId).HasName("PK__Membersh__322035ECCE092DB1");

            entity.ToTable("MembershipPackage");

            entity.Property(e => e.PackageId).HasColumnName("PackageID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MaxChildren).HasDefaultValue(1);
            entity.Property(e => e.PackageName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payment__9B556A5832908430");

            entity.ToTable("Payment");

            entity.Property(e => e.PaymentId).HasColumnName("PaymentID");
            entity.Property(e => e.Amount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.InvoiceNumber).HasMaxLength(50);
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.PackageId).HasColumnName("PackageID");
            entity.Property(e => e.PaymentMethod).HasMaxLength(50);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("Pending");
            entity.Property(e => e.TransactionDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TransactionId)
                .HasMaxLength(100)
                .HasColumnName("TransactionID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Package).WithMany(p => p.Payments)
                .HasForeignKey(d => d.PackageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payment__Package__6C190EBB");

            entity.HasOne(d => d.User).WithMany(p => p.Payments)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payment__UserID__6B24EA82");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__8AFACE3A39B3DA52");

            entity.ToTable("Role");

            entity.HasIndex(e => e.RoleName, "UQ__Role__8A2B61600A74F94D").IsUnique();

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__1788CCACF3A6C054");

            entity.ToTable("User");

            entity.HasIndex(e => e.Email, "UQ__User__A9D10534DEA55E55").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Address).HasMaxLength(250);
            entity.Property(e => e.DoctorCode).HasMaxLength(20);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsTrial).HasDefaultValue(false);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.PositionId).HasColumnName("PositionID");
            entity.Property(e => e.RegistrationDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.RoleId).HasColumnName("RoleID");

            entity.HasOne(d => d.Position).WithMany(p => p.Users)
                .HasForeignKey(d => d.PositionId)
                .HasConstraintName("FK__User__PositionID__4316F928");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__User__RoleID__4222D4EF");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}